### ISSUE TITLE
Small writing errors

### ISSUE THREAD

**Issue by TheFi5h** [hso-ecruise/ecruise-backend#16]
When creating the assemblers i found some spelling errors in a few classes. Here's a list of them:

- `InvoiceEntity.Payed -> Paid`
- `CharingStationModel.SlotsOccupuied -> Occupied`
- `MaintenanceModel.MaintenenaceId -> MaintenanceId`

Since i was on a different branch and dont know if anyone has got some local branches, too, I didn't want to refactor them immediately.
Let's talk about when we could rafactor that to minimize merging errors because of branches, because the properties are getting used in several files.

**Comment by Lyrex** [comment]
Fixed by Commit 4221af9c723116d660b4fdfd8fd41f360052b4eb and already live.
