### ISSUE TITLE
Endpoint GET /invoices/items/{InvoiceItemId} does not work

### ISSUE THREAD

**Issue by Lyrex** [hso-ecruise/ecruise-backend#19]
The endpoint `GET /invoices/items/{InvoiceItemId}` does not work, since it does match the second parameter being an `InvoiceId`.
This results in the backend trying to match the above mentioned endpoint as `GET /invoices/{InvoiceId}/{InvoiceItemId}` with `{InvoiceId}` being `string: "items"` which does not exist.

**Comment by TheFi5h** [comment]
Looks like you already fixed that this morning. Im going to close the bug.
