### ISSUE TITLE
Using string as method parameter conflicts with API spec

### ISSUE THREAD

**Issue by Lyrex** [hso-ecruise/ecruise-backend#8]
Using the parameter type string in controller routes possibly conflicts with the API spec.
The API specification says, that a string in the body has to be encapsulated in an object but the string parameter type requires the content to be only the non-encapsulated string.

Here's an example to make it easier to understand:
I'm using `PATCH /customers/{CustomerId}/email` as example.

In the API we specify that the body has to be in the following format: 
```
{
  "Email": "user@example.com"
}
```

In ASP.NET Core we use the following definition:
```csharp
[HttpPatch("{id}/email", Name = "UpdateCustomerEmail")]
public IActionResult UpdateEmail(uint id, [FromBody] string email)
```
which required the body to be `"user@example.com"` instead of the whole object shown above.

This conflicts and needs to be resolved.

**Comment by TheFi5h** [comment]
You're right. Just tested it a bit e.g. with taking multiple [FromBody] parameters. But it really just wants a single string. Not even a plain json object
`{
    "password": "xyz"
}`
did work.

As a possible solution:
Maybe define very simple objects which carry only the password variable, so we could parse the json to the password Object?

**Comment by Lyrex** [comment]
Won't work unless we create a helper object for every single string since the name of the object's string attribute has to match the identifier in the API Spec.
I guess the easiest was to change the API Specification to accept non-object wrapped string.

**Comment by TheFi5h** [comment]
will work, too, but then it becomes inconsistent with the rest of the api

**Comment by Lyrex** [comment]
I changed all the API PATCH methods to match the backend implementation by only providing the non-encapsulated data type.
Could you please review this one and comment if we want to apply this to our live API?

[swagger-api-patch-review.yaml.txt](https://github.com/hso-ecruise/ecruise-backend/files/1040640/swagger-api-patch-review.yaml.txt)
_(hint: don't forget to rename the file extension back to .yaml. GitHub doesn't like yaml files)_

**Comment by TheFi5h** [comment]
I reviewed the changes and think they are OK. I made some small adaptations concerning the customers' POST method and the PATCH method for /customers/{CustomerId}/address
